### ISSUE TITLE
When I use “pyinstaller” to export py as exe, it shows the following

### ISSUE THREAD

**Issue by haaabb** [bastibe/transplant#100]
Traceback (most recent call last):
  File "mainwindow.py", line 40, in <module>
    matlab = transplant.Matlab(jvm=False)
  File "transplant\transplant_master.py", line 542, in __init__
  File "transplant\transplant_master.py", line 711, in _locate_libzmq
RuntimeError: could not locate libzmq for Matlab

When I run the program in pycharm, it runs normally, but after packaging it into an exe file, the exe file cannot run normally.
Thank you very much！！！

**Comment by haaabb** [comment]
I remember that I installed the library with anaconda. I have no problem running it on pycharm, but the above problem occurs after packaging it into an exe

**Comment by bastibe** [comment]
As you can see [in the code](https://github.com/bastibe/transplant/blob/master/transplant/transplant_master.py#L693), transplant searches for libzmq in your PATH, and in C:/Program Files/ZeroMQ*/bin (which is the default directory if you install libzmq using the official installers from http://wiki.zeromq.org/intro:get-the-software).

If Matlab can't find an appropriate compiler, try installing MinGW in Matlab's own app store thing. That seems to work relatively reliably.
