### ISSUE TITLE
Unicode problem?

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#49]
I got this issue from a user when using transplant on MacOS with my compiled code:
```
Last login: Fri Aug 11 11:31:29 on ttys000
[rosss-imac:~] rossstewart% python3
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> spinw='/Applications/pyspinw.app/pyspinw.sh'
>>> from transplant import Matlab
>>> from transplant import MatlabStruct
>>> import numpy as np
>>> m=Matlab(spinw)
SpinW process is running...
>>> tri = m.sw_model('triAF',1.)
Preparing 'triAF' model ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/transplant/transplant_master.py", line 124, in reader
    print(line.decode(), end='')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 41: invalid continuation byte
```
It seems it is related to a problem that we solved before by changing the encoding in MATLAB to UTF-8. I compiled the MATLAB code after fixing this issue and it works fine on my machine. Just wanted to ask if you have any idea whether there might be some setting in Python/terminal which also has an effect.
The original string in MATLAB that caused the error was:
`Creating the bond list (maxDistance = 10 Å, nCell = 7x5x2)...`
seemingly the Angstrom symbol (which is at position 42) is responsible.

Seems I have to remove these special symbols from the output of my code.
Any idea is welcome!

**Comment by bastibe** [comment]
Thank you for reporting this bug.

This is very strange. [dumpmsgpack.m:135](https://github.com/bastibe/transplant/blob/master/transplant/dumpmsgpack.m#L135) clearly encodes strings as UTF-8, and the error message clearly states that Python is trying to decode UTF-8 as well.

Moreover, the two ways of writing `'Å'` in Unicode that I know of are `LATIN CAPITAL LETTER A WITH RING ABOVE` and `A` + `COMBINING RING ABOVE`. According to your pasted text and the byte position, you are using the former encoding. This would encode as `0xc3 0x85` (`0b11000011 10000101`). Your error message shows `0xc5`, however, or in binary, `0b11000101`. 

Since the first three bit are `0b110`, this is the first byte of a two-byte character, which should then be `0b101xxxxxx` (the `x`s would be contained in the second byte). This encompasses the Unicode value range from `0x140` to `0x17F`, which does not contain any useful letters for displaying `Å`. 

*However*, `0xc5` itself is the codepoint of `Å` in *unencoded* Latin 1. My guess is, therefore, that for some reason, Matlab did not encode this string as UTF-8. This means that this string somehow did not pass through [dumpmsgpack.m:dumpstring](https://github.com/bastibe/transplant/blob/master/transplant/dumpmsgpack.m#L132). The error message says that it was still msgpack-encoded as a string, though.

This is a fascinating riddle. Can you create a minimal test case that reproduces this error on your machine?

**Comment by bastibe** [comment]
Some more experimentation shows that older versions of Matlab's text editor on macOS seem to misrepresent characters: You can write them to the file just fine, and they will look OK in the editor, but save them and re-open the file and they are corrupt. Maybe something like this is going on?
