### ISSUE TITLE
/sys/os/glnxa64/libstdc++ and GLIBCXX_3.4.20

### ISSUE THREAD

**Issue by sirgogo** [bastibe/transplant#64]
Hi, I'm getting some issues loading the matlab engine. Before, it used to work fine. But upon install on a new machine, running into an error despite following the same steps.

The error:
```
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transplant
>>> eng = transplant.Matlab()

                            < M A T L A B (R) >
                  Copyright 1984-2016 The MathWorks, Inc.
                   R2016a (9.0.0.341360) 64-bit (glnxa64)
                             February 11, 2016

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Error loading libzmq: There was an error loading the library "/opt/conda/lib/libzmq.so.5"
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/conda/lib/libzmq.so.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/transplant/transplant_master.py", line 490, in __init__
    self.eval('0;') # no-op. Wait for Matlab startup to complete.
  File "/opt/conda/lib/python3.6/site-packages/transplant/transplant_master.py", line 548, in __getattr__
    return self._get_global(name)
  File "/opt/conda/lib/python3.6/site-packages/transplant/transplant_master.py", line 92, in _get_global
    response = self.send_message('get_global', name=name)
  File "/opt/conda/lib/python3.6/site-packages/transplant/transplant_master.py", line 148, in send_message
    self._wait_socket(zmq.POLLOUT)
  File "/opt/conda/lib/python3.6/site-packages/transplant/transplant_master.py", line 178, in _wait_socket
    raise RuntimeError('Process died unexpectedly')
RuntimeError: Process died unexpectedly
>>> 
```

Some verifications:
```
$ ls -al /opt/conda/lib/libzmq.so.5*
lrwxrwxrwx 1 root root     15 Jul 12 16:54 /opt/conda/lib/libzmq.so.5 -> libzmq.so.5.1.5
-rwxrwxr-x 2 root root 745392 Apr 13 09:38 /opt/conda/lib/libzmq.so.5.1.5
```

```
$ ls -al /opt/conda/lib/libstdc++.so.6*
lrwxrwxrwx 1 root root      19 Jul 12 17:40 /opt/conda/lib/libstdc++.so.6 -> libstdc++.so.6.0.19
-rwxrwxr-x 2 root root 1055192 Nov 15  2016 /opt/conda/lib/libstdc++.so.6.0.19
-rw-rw-r-- 1 root root    2311 Jul 12 17:40 /opt/conda/lib/libstdc++.so.6.0.19-gdb.py
lrwxrwxrwx 1 root root      19 Jul 12 17:43 /opt/conda/lib/libstdc++.so.6.0.21 -> libstdc++.so.6.0.24
-rwxrwxr-x 2 root root 8167184 Mar  8 10:42 /opt/conda/lib/libstdc++.so.6.0.24
```

```
$ ls -al /usr/lib64/libstdc++.so.6*
lrwxrwxrwx. 1 root root     19 Jul 12 15:12 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.19
-rwxr-xr-x. 1 root root 991616 May 15 14:52 /usr/lib64/libstdc++.so.6.0.19
```

I even moved the libstdc++.so files out of that directory:
```
$ ls -al /usr/local/MATLAB/R2016a/sys/os/glnxa64
total 27812
drwxrwxr-x 2 root root      291 Jul 12 18:15 .
drwxrwxr-x 3 root root       70 Jul 12 18:15 ..
-r-xr-xr-x 1 root root   521073 Dec 28  2015 libgcc_s.so.1
lrwxrwxrwx 1 root root       20 Jul 12 16:57 libgfortran.so.3 -> libgfortran.so.3.0.0
-r-xr-xr-x 1 root root  5811979 Dec 28  2015 libgfortran.so.3.0.0
-r-xr-xr-x 1 root root  1303868 Dec 28  2015 libifcore.so.5
-r-xr-xr-x 1 root root   196634 Dec 28  2015 libifport.so.5
-r-xr-xr-x 1 root root  3083165 Dec 28  2015 libimf.so
-r-xr-xr-x 1 root root   397899 Dec 28  2015 libintlc.so.5
-r-xr-xr-x 1 root root  1380283 Dec 28  2015 libiomp5.so
-r-xr-xr-x 1 root root   397899 Dec 28  2015 libirc.so
lrwxrwxrwx 1 root root       20 Jul 12 16:57 libquadmath.so.0 -> libquadmath.so.0.0.0
-r-xr-xr-x 1 root root   866238 Dec 28  2015 libquadmath.so.0.0.0
-r-xr-xr-x 1 root root 14494114 Dec 28  2015 libsvml.so
-r--r--r-- 1 root root      291 Dec 28  2015 README.libstdc++
```

Any ideas?

**Comment by sirgogo** [comment]
@bastibe I already moved the libstdc++.so files out of the MATLAB directory, but it didn't help. It also asks for GLIBCXX_3.4.20 rather than GLIBCXX_3.4.21 if that makes a difference?

**Comment by bastibe** [comment]
I see! You should probably try to make Matlab use the same glibc as conda, probably by `LD_PRELOAD`ing conda's library.

**Comment by bastibe** [comment]
Alternatively, you can try installing libzmq with your computer's package manager. If I remember correctly, Transplant will prefer the system's libzmq over conda's, which should also fix your problem since the system's libzmq will use the same glibc as Matlab if you remove Matlab's glibc.

**Comment by bastibe** [comment]
In this case, it might have been a weird interaction between conda and Matlab, where Transplant for some reason chose to use conda's libzmq, which was compiled against a different glibc than the rest of the system.
