### ISSUE TITLE
Directory error on a remote machine 

### ISSUE THREAD

**Issue by nimamanaf** [bastibe/transplant#66]
Hi, 
I am trying to use the transplant module in a remote linux machine. Matlab is already installed there. How can I give the directory to the installed matlab in the remote machine?
I get the floowing error after importing the module.

Best,  

eng = transplant.Matlab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/kuacc/users/ndizbin14/anaconda3/lib/python3.6/site-packages/transplant/transplant_master.py", line 487, in __init__
    self.process = Popen(process_arguments, stdin=DEVNULL, stdout=PIPE)
  File "/kuacc/users/ndizbin14/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/kuacc/users/ndizbin14/anaconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'matlab'

**Comment by bastibe** [comment]
As per the README:

> If you want to use a different version of Matlab, or `matlab` is not in PATH, use `Matlab(executable='/path/to/matlab')`.
