### ISSUE TITLE
plot regression ?

### ISSUE THREAD

**Issue by kupiqu** [bastibe/transplant#77]
plotting seems to crash transplant

```
matlab.plot([1,2,3])
matlab.drawnow()
```

```
Traceback (most recent call last):
  File "pyTransplantMatlabTest.py", line 5, in <module>
    matlab.plot([1,2,3])
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/transplant/transplant_master.py", line 454, in __call__
    return self._parent._call(self._fun, args, nargout=nargout)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/transplant/transplant_master.py", line 618, in _call
    nargout=nargout)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/transplant/transplant_master.py", line 174, in send_message
    response['stack'], response['identifier'], response['message'])
transplant.transplant_master.TransplantError: Invalid data argument. (MATLAB:plot:InvalidFirstInput)
Traceback (most recent call last):
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/transplant/transplant_remote.m", line 129, in transplant_remote
    [results{:}] = fun(args{:});
```

**Comment by kupiqu** [comment]
messages before the crash:

```
receiving msg:
{"name":"plot","type":"get_global"}
msg received.
sending msg:
{"type":"value","value":["__function__","plot"]}
msg sent.
receiving msg:
{"name":"plot","args":[[1,2,3]],"nargout":-1,"type":"call"}
msg received.
sending msg:
{"identifier":"MATLAB:plot:InvalidFirstInput","message":"Invalid data argument.","stack":{"file":"\/home\/miniconda\/envs\/cenv1\/lib\/python3.7\/site-packages\/transplant\/transplant_remote.m","name":"transplant_remote","line":129},"type":"error"}
msg sent.
```

**Comment by bastibe** [comment]
`matlab.plot([1, 2, 3])` tries to plot `[1, 2, 3]`, which is a list. In Matlab, this translates to a cell array. Matlab can't plot cell arrays.

If you want to pass Matlab arrays, use numpy arrays, such as `matlab.plot(numpy.arange(3))`.

**Comment by kupiqu** [comment]
> `matlab.plot([1, 2, 3])` tries to plot `[1, 2, 3]`, which is a list. In Matlab, this translates to a cell array. Matlab can't plot cell arrays.
> 
> If you want to pass Matlab arrays, use numpy arrays, such as `matlab.plot(numpy.arange(3))`.

Sure, I know about that, but I was expecting that anything following `matlab.` would be interpreted as m-code. It isn't the case, which seems counterintuitive.
