### ISSUE TITLE
RuntimeError: could not locate libzmq for Matlab

### ISSUE THREAD

**Issue by TIMESTICKING** [bastibe/transplant#98]
after running this
`transplant.Matlab()`
error comes up
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\program files\python37\lib\site-packages\transplant\transplant_master.py", line 542, in __init__
    msgformat, zmq_address, self._locate_libzmq()
  File "c:\program files\python37\lib\site-packages\transplant\transplant_master.py", line 711, in _locate_libzmq
    raise RuntimeError('could not locate libzmq for Matlab')
RuntimeError: could not locate libzmq for Matlab
```

what causes it plz?
i'm using windows 10 and py3.7 and matlab2021b

**Comment by bastibe** [comment]
Did you install libzmq?

**Comment by pokjnb** [comment]
@TIMESTICKING  you havent install libzmq . 
I found that 'pip installing zmq' not include 'libzmq'
maybe need to install zeromq alone.
I am windows 10 too, and I failed, any progress of you?

**Comment by TIMESTICKING** [comment]
> 

no, i give up this way, instead, MatLab official provides package matlab.engine for python, so i'd use that.

**Comment by bastibe** [comment]
You need to install libzmq, either with their official installer, or through conda, or by putting the library on PATH otherwise.
